---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wiremock
parameters:
  - name: ENV_NAME
    value: env-wiremock
  - name: WIREMOCK_IMAGE
    value: quay.io/cloudservices/wiremock
  - name: WIREMOCK_IMAGE_TAG
    value: 3.9.1
  - name: MEMORY_REQUEST
    value: 256Mi
  - name: MEMORY_LIMIT
    value: 512Mi
  - name: CPU_REQUEST
    value: 150m
  - name: CPU_LIMIT
    value: 300m
  - name: SUBSCRIPTION_SEARCH_URL
    value: placeholder
  - name: PARTNER_ENTITLEMENT_URL
    value: placeholder
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: wiremock
      labels:
        app: wiremock
    spec:
      envName: ${ENV_NAME}

      deployments:
        - name: service
          replicas: 1
          webServices:
            public:
              enabled: true
          podSpec:
            image: ${WIREMOCK_IMAGE}:${WIREMOCK_IMAGE_TAG}
            resources:
              requests:
                cpu: ${CPU_REQUEST}
                memory: ${MEMORY_REQUEST}
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
            env:
              - name: WIREMOCK_OPTIONS
                value: --port=8000
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /__admin/health
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /__admin/health
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 5
            volumeMounts:
            - name: swatch-proxy-mappings
              mountPath: /home/wiremock/mappings
            volumes:
            - name: swatch-proxy-mappings
              configMap:
                name: proxy-mappings

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: proxy-mappings
    data:
      subscription-search-api-proxy.json: |-
        {
          "priority": 10,
          "request": {
            "method": "ANY",
            "urlPattern": "/search/criteria;.*"
          },
          "response": {
            "proxyBaseUrl": "${SUBSCRIPTION_SEARCH_URL}"
          }
        }
      partner-entitlement-api-proxy.json: |-
        {
          "priority": 10,
          "request": {
            "method": "ANY",
            "urlPattern": "/partnerApi/v1/partnerSubscriptions"
          },
          "response": {
            "proxyBaseUrl": "${PARTNER_ENTITLEMENT_URL}"
          }
        }


